[package]
name = "umegaemochi"
version = "0.1.0"
description = "A Tauri App"
authors = ["yadokani389"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
reqwest = "0.12.9"
quick-xml = "0.37.0"
localip = "0.2.1"
tauri-api = "0.7.6"
warp = "0.3.7"
serde_json = "1.0.134"
