name: 'Publish Linux Arm builds'

on:
  workflow_dispatch:
    inputs:
      dont_publish:
        required: false
        default: true
        type: boolean
  push:
    branches:
      - release

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [aarch64]
        include:
          - arch: aarch64
            cpu: cortex-a72
            base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bookworm.img.xz
            deb: arm64
            rpm: aarch64
            appimage: aarch64

    steps:
      - uses: actions/checkout@v3

      - name: Cache rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-on-failure: true

      - name: Build app
        uses: pguyot/arm-runner-action@v2.6.5
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          bind_mount_repository: true
          image_additional_mb: 10240
          optimize_image: no
          #exit_on_fail: no
          commands: |
            # Prevent Rust from complaining about $HOME not matching eid home
            export HOME=/root

            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

            # Install setup prerequisites
            apt-get update -y --allow-releaseinfo-change
            apt-get autoremove -y
            apt-get install -y --no-install-recommends --no-install-suggests curl libwebkit2gtk-4.1-dev build-essential libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf libfuse2 file
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            . "$HOME/.cargo/env"
            curl -fsSL https://deb.nodesource.com/setup_lts.x | bash
            apt-get install -y nodejs

            # Install frontend dependencies
            npm install -g pnpm
            pnpm install

            # Build the application
            pnpm run tauri build -- --verbose

      - name: Get app version
        run: echo "APP_VERSION=$(jq -r .version src-tauri/tauri.conf.json)" >> $GITHUB_ENV

      - name: Upload deb bundle
        uses: actions/upload-artifact@v3
        with:
          name: Debian Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/deb/umegaemochi_${{ env.APP_VERSION }}_${{ matrix.deb }}.deb

      - name: Upload rpm bundle
        uses: actions/upload-artifact@v3
        with:
          name: RPM Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/rpm/umegaemochi-${{ env.APP_VERSION }}-1.${{ matrix.rpm }}.rpm

      - name: Upload appimage bundle
        uses: actions/upload-artifact@v3
        with:
          name: AppImage Bundle
          path: ${{ github.workspace }}/src-tauri/target/release/bundle/appimage/umegaemochi_${{ env.APP_VERSION }}_${{ matrix.appimage }}.AppImage

      - name: Upload deb bundle to release
        uses: svenstaro/upload-release-action@v2
        if: inputs.dont_publish == false
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/deb/umegaemochi_${{ env.APP_VERSION }}_${{ matrix.deb }}.deb
          tag: v${{ env.APP_VERSION }}
          overwrite: true
          draft: true
          body: 'See the assets to download this version and install.'

      - name: Upload rpm bundle to release
        uses: svenstaro/upload-release-action@v2
        if: inputs.dont_publish == false
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/rpm/umegaemochi-${{ env.APP_VERSION }}-1.${{ matrix.rpm }}.rpm
          tag: v${{ env.APP_VERSION }}
          overwrite: true
          draft: true
          body: 'See the assets to download this version and install.'

      - name: Upload appimage bundle to release
        uses: svenstaro/upload-release-action@v2
        if: inputs.dont_publish == false
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/appimage/umegaemochi_${{ env.APP_VERSION }}_${{ matrix.appimage }}.AppImage
          tag: v${{ env.APP_VERSION }}
          overwrite: true
          draft: true
          body: 'See the assets to download this version and install.'
